const ICD_CODE_MAP = {
  "J42": "Chronic bronchitis, unspecified",
  "J43.0": "Unilateral emphysema",
  "J43.1": "Panlobular emphysema",
  "J43.2": "Centrilobular emphysema",
  "J43.8": "Other emphysema",
  "J43.9": "Emphysema, unspecified",
  "J98.2": "Interstitial emphysema",
  "J98.3": "Compensatory emphysema",
  "N18.1": "Chronic kidney disease, stage 1",
  "N18.2": "Chronic kidney disease, stage 2",
  "N18.3": "Chronic kidney disease, stage 3",
  "N18.9": "Chronic kidney disease, unspecified",
  "N18.4": "Chronic kidney disease, stage 4",
  "N18.5": "Chronic kidney disease, stage 5",
  "N18.6": "End-stage renal disease",
  "I27.8": "Other specified pulmonary heart diseases",
  "I27.9": "Pulmonary heart disease, unspecified",
  "J40": "Bronchitis, not specified as acute or chronic",
  "J41": "Simple and mucopurulent chronic bronchitis",
  "J44": "Other chronic obstructive pulmonary disease",
  "J47": "Bronchiectasis",
  "J60": "Coal workers’ pneumoconiosis",
  "J61": "Pneumoconiosis due to asbestos and other mineral fibers",
  "J62": "Pneumoconiosis due to dust containing silica",
  "J63": "Pneumoconiosis due to other inorganic dusts",
  "J64": "Unspecified pneumoconiosis",
  "J65": "Pneumoconiosis associated with tuberculosis",
  "J66": "Airway disease due to organic dust",
  "J68.4": "Chronic respiratory conditions due to inhalation of chemicals",
  "J70.1": "Acute pulmonary manifestations due to radiation",
  "J70.3": "Chronic and unspecified respiratory conditions due to radiation",
  "I21": "Acute myocardial infarction",
  "I22": "Subsequent myocardial infarction",
  "I25.2": "Old myocardial infarction",
  "I50": "Heart failure",
  "I11.0": "Hypertensive heart disease with heart failure",
  "I09.9": "Rheumatic heart disease, unspecified",
  "I25.5": "Ischemic cardiomyopathy",
  "I42.0": "Dilated cardiomyopathy",
  "I42.5": "Restrictive cardiomyopathy",
  "I42.6": "Alcoholic cardiomyopathy",
  "I42.7": "Cardiomyopathy due to drug and toxin exposure",
  "I42.8": "Other cardiomyopathies",
  "I42.9": "Cardiomyopathy, unspecified",
  "I43": "Cardiomyopathy in diseases classified elsewhere",
  "K73": "Chronic hepatitis, unspecified",
  "B16": "Acute hepatitis B",
  "B18.0": "Chronic viral hepatitis B with delta-agent",
  "B18.1": "Chronic viral hepatitis B without delta-agent",
  "B19.1": "Unspecified viral hepatitis B",
  "B19.2": "Unspecified viral hepatitis C",
  "E10": "Type 1 diabetes mellitus",
  "E11": "Type 2 diabetes mellitus",
  "E11.621": "Type 2 diabetes mellitus with foot ulcer",
  "E11.641": "Type 2 diabetes mellitus with hypoglycemia without coma",
  "E11.649": "Type 2 diabetes mellitus with hypoglycemia with coma",
  "E11.65": "Type 2 diabetes mellitus with hyperglycemia",
  "I13.10": "Hypertensive heart and chronic kidney disease, stage 1-4",
  "I12.0": "Hypertensive chronic kidney disease, stage 5 or ESRD",
  "I13.11": "Hypertensive heart and chronic kidney disease with heart failure",
  "I12.9": "Hypertensive chronic kidney disease, stage 1-4",
  "I13.0": "Hypertensive heart and chronic kidney disease without heart failure",
  "E10.21": "Type 1 diabetes mellitus with diabetic nephropathy",
  "E08.22": "Diabetes mellitus due to underlying condition with diabetic chronic kidney disease",
  "E08.29": "Diabetes mellitus due to underlying condition with other diabetic kidney complications",
  "E09.21": "Drug- or chemical-induced diabetes mellitus with diabetic nephropathy",
  "E09.29": "Drug- or chemical-induced diabetes mellitus with other kidney complications",
  "E10.22": "Type 1 diabetes mellitus with diabetic chronic kidney disease",
  "E10.29": "Type 1 diabetes mellitus with other diabetic kidney complications",
  "E11.21": "Type 2 diabetes mellitus with diabetic nephropathy",
  "E11.22": "Type 2 diabetes mellitus with diabetic chronic kidney disease",
  "E11.29": "Type 2 diabetes mellitus with other diabetic kidney complications",
  "E13.21": "Other specified diabetes mellitus with diabetic nephropathy",
  "E13.22": "Other specified diabetes mellitus with diabetic chronic kidney disease",
  "E13.29": "Other specified diabetes mellitus with other diabetic kidney complications",
  "E11.40": "Type 2 diabetes mellitus with diabetic neuropathy",
  "I13.2": "Hypertensive heart and chronic kidney disease with ESRD",
  "K71.7": "Toxic liver disease with fibrosis and cirrhosis of liver",
  "E12": "Malnutrition-related diabetes mellitus",
  "E13": "Other specified diabetes mellitus",
  "E14": "Unspecified diabetes mellitus",
  "C18": "Malignant neoplasm of colon",
  "C19": "Malignant neoplasm of rectosigmoid junction",
  "C20": "Malignant neoplasm of rectum",
  "C21": "Malignant neoplasm of anus and anal canal",
  "C33": "Malignant neoplasm of trachea",
  "C34": "Malignant neoplasm of bronchus and lung",
  "C38.4": "Malignant neoplasm of pleura",
  "C45.0": "Mesothelioma of pleura",
  "C46.71": "Kaposi's sarcoma of lung",
  "C50": "Malignant neoplasm of breast",
  "C53": "Malignant neoplasm of cervix uteri",
  "C61": "Malignant neoplasm of prostate",
  "D01.0": "Carcinoma in situ of colon",
  "D01.2": "Carcinoma in situ of rectosigmoid junction",
  "D01.3": "Carcinoma in situ of rectum",
  "D02.2": "Carcinoma in situ of bronchus and lung",
  "D05": "Carcinoma in situ of breast",
  "D06": "Carcinoma in situ of cervix uteri",
  "D07.5": "Carcinoma in situ of prostate",
  "C77": "Secondary and unspecified malignant neoplasm of lymph nodes",
  "C78": "Secondary malignant neoplasm of respiratory and digestive organs",
  "C79": "Secondary malignant neoplasm of other sites",
  "C80": "Malignant neoplasm without specification of site",
  "C81": "Hodgkin lymphoma",
  "C82": "Follicular lymphoma",
  "C83": "Diffuse non-Hodgkin lymphoma",
  "C84": "Mature T/NK-cell lymphomas",
  "C85": "Other specified and unspecified types of non-Hodgkin lymphoma",
  "C88": "Malignant immunoproliferative diseases",
  "C90.0": "Multiple myeloma",
  "C90.2": "Plasma cell leukemia",
  "C96": "Other and unspecified malignant neoplasms of lymphoid, hematopoietic and related tissue",
};

module.exports = { ICD_CODE_MAP };
